language: groovy #
jdk:
  - openjdk8 #
sudo: false #
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/ #
addons:
  postgresql: "9.6"
services:
  - postgresql
  - docker
script:
  - cp src/test/resource/application-test.yml.travis src/main/resources/application-test.yml
  - ls src/main/resources/
  - cat src/main/resources/application-test.yml
  - ./gradlew clean
  - ./gradlew build
  - echo "$docker_token" | docker login -u "$docker_user" --password-stdin
  - ./gradlew dockerPublish
