micronaut:
  application:
    name: mapper-mn
  server:
    max-request-size: 4mb
    multipart.max-file-size: 4mb  #todo remove when bug fixed https://github.com/micronaut-projects/micronaut-core/issues/1882
    netty.log-level: DEBUG
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
        path: /api/login
      oauth:
        enabled: true
        path: /api/oauth/access_token
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: thisiscoolbutstillshouldbechanged
---
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/nsl
    username: nsl
    password: nsl
    driverClassName: org.postgresql.Driver
    autoCommit: false
    schema: mapper
    socketTimeout: 30
---
mapper:
  brokerRegex: ^(https?://[^/]*)?/broker/(.*?)(/api/.*?)?(\.json|\.xml|\.rdf|\.html)?$
  urlRegex: ^(https?://[^/]*)?/?(.*?)(/api/.*?)?(\.json|\.xml|\.rdf|\.html)?$

