micronaut:
  application:
    name: mapper-mn
  server:
    max-request-size: 4194304  # 4mb
    multipart.max-file-size: 4194304  #todo remove when bug fixed https://github.com/micronaut-projects/micronaut-core/issues/1882
    netty.log-level: DEBUG
    thread-selection: AUTO
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  security:
    authentication: bearer
    intercept-url-map:
      - pattern: /**
        access:
        - isAnonymous()
      - pattern: /swagger/**
        access:
        - isAnonymous()
    endpoints:
      login:
        path: /api/login
      oauth:
        path: /api/oauth/access_token
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${mapper.jwt.refSecret:TRDPt6JXkeXcCzvEQs3BKJBkshdbkjhsksjdKJB}
---
micronaut:
  security:
    token:
      jwt:
        generator:
          access-token:
            expiration: 3600
          refresh-token:
            secret: ${mapper.jwt.refSecret:QRJyxmRjnP8zd7j46GVDlaksbLJIEGDblkjsfdjk}
---
mapper:
  brokerRegex: ^(https?://[^/]*)?/broker/(.*?)(/api/.*?)?(\.json|\.xml|\.rdf|\.html)?$
  urlRegex: ^(https?://[^/]*)?/?(.*?)(/api/.*?)?(\.json|\.xml|\.rdf|\.html)?$
---
datasources:
  default:
    url: ${mapper.db.url:`jdbc:postgresql://localhost:5432/nsl`}
    username: ${mapper.db.username:nsl}
    password: ${mapper.db.password:nsl}
    driverClassName: org.postgresql.Driver
    autoCommit: false
    schema: mapper
    socketTimeout: 30
